version: "3"

services:
  bare: &app
    image: node:12
    command: bash
    working_dir: /app/
    command: yarn dev
    volumes:
      - ./:/app/
      - yarn-cache:/usr/local/share/.cache/yarn/v2
      - node_modules:/app/node_modules/
    environment: {}

volumes:
  node_modules: {}
  yarn-cache: {
    external: true
  }
