version: "3"

services:
  bare: &app
    image: node:12
    command: bash
    working_dir: /app/
    command: yarn dev
    volumes:
      - ./:/app/
      - yarn-cache:/usr/local/share/.cache/yarn/v2
      - node_modules:/app/node_modules/
      - .stryker-tmp
      - ./output
    environment:
      STRYKER_DASHBOARD_API_KEY: "${STRYKER_DASHBOARD_API_KEY}-invalid"
      NPM_TOKEN: "${NPM_TOKEN}-invalid"


volumes:
  node_modules: {}
  yarn-cache: {
    external: true
  }
