format_version: 2

pipelines:
  analytics-sdk-generator-test:
    group: analytics-sdk-generator
    label_template: "${git-analytics-sdk-generator[:8]}"
    lock_behavior: unlockWhenFinished
    timer:
      spec: "* * * * * ? */15"
      only_on_changes: yes
    materials:
      git-analytics-sdk-generator:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/leprechaun/analytics-sdk-generator.git
          branchwhitelist: master,test-*
        destination: ./

    environment_variables:
      GO_AUTOMATION_USER: automaton
      GITHUB_AUTOMATION_USER: gocd-service-account
    secure_variables:
      GO_AUTOMATION_PASSWORD: "AES:+heX4S6WsUXSqPxj5nNOoQ==:9jXtfK+GoUYDpS7mvGGWmA=="
      GITHUB_AUTOMATION_PASSWORD: "AES:EwOyEBf7z5d8VzVua75pEg==:LZhYZmLP7OR2Vf+NwirNlTCYCmptgbSRRqD3kWjjYlXxxCeSZGYyX07ZIcgMpfhV"
      NPM_TOKEN: "AES:6sBhU7v8kXP+ewzXZ9yywA==:r8ekub2kRBDTLbtrvGzqndsQfHNGSl+IRM3UFTuXkMuQvgeePCIjfEQSyOm0rTlg"
    stages:
      - tests:
          jobs:
            tests:
              tasks:
                - script: |
                    ./auto/test --coverage
                    docker run -v `pwd`:/tmp/mount alpine chown -R $(id -u):$(id -g) /tmp/mount
                - script: |
                    ./auto/clean-up || true
            audit:
              tasks:
                - script: |
                    ./auto/clean-up || true
                - script: |
                    ./auto/audit --json --groups dependencies --level moderate

  analytics-sdk-generator-build:
    group: analytics-sdk-generator
    label_template: "0.1.${COUNT}-${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: analytics-sdk-generator-test
        stage: tests
      git-analytics-sdk-generator:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/leprechaun/analytics-sdk-generator.git
          branchwhitelist: master,test-*
        destination: ./

    environment_variables: {}
    secure_variables:
      NPM_TOKEN: "AES:6sBhU7v8kXP+ewzXZ9yywA==:r8ekub2kRBDTLbtrvGzqndsQfHNGSl+IRM3UFTuXkMuQvgeePCIjfEQSyOm0rTlg"
    stages:
      - package:
          tasks:
            - script: |
               set -e
               function finish {
                  EXIT_CODE=$?
                  docker run -v `pwd`:/tmp/mount alpine chown -R $(id -u):$(id -g) /tmp/mount
                  ./auto/clean-up || true
                  exit $EXIT_CODE
                }
                trap finish EXIT

                ./auto/build
                ./auto/publish --new-version ${GO_PIPELINE_LABEL} --tag beta

  analytics-sdk-generator-publish:
    group: analytics-sdk-generator
    label_template: "${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: analytics-sdk-generator-build
        stage: package
    environment_variables: {}
    secure_variables:
      NPM_TOKEN: "AES:6sBhU7v8kXP+ewzXZ9yywA==:r8ekub2kRBDTLbtrvGzqndsQfHNGSl+IRM3UFTuXkMuQvgeePCIjfEQSyOm0rTlg"
    stages:
      - publish:
          jobs:
            publish:
              tasks:
                - script: |
                   set -e
                   function finish {
                      EXIT_CODE=$?
                      docker run -v `pwd`:/tmp/mount alpine chown -R $(id -u):$(id -g) /tmp/mount
                      ./auto/clean-up || true
                      exit $EXIT_CODE
                    }
                    trap finish EXIT

                    ./auto/build
                    ./auto/yarn publish --new-version "$(echo $GO_PIPELINE_LABEL | awk -F '-' '{print $1}')"
