format_version: 2

pipelines:
  analytics-sdk-generator-test:
    group: analytics-sdk-generator
    label_template: "${git-analytics-sdk-generator[:8]}"
    lock_behavior: unlockWhenFinished
    timer:
      spec: "* * * * * ? */15"
      only_on_changes: yes
    materials:
      git-analytics-sdk-generator:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/leprechaun/analytics-sdk-generator.git
          branchwhitelist: master,test-*
        destination: ./

    environment_variables:
      GO_AUTOMATION_USER: automaton
      GITHUB_AUTOMATION_USER: gocd-service-account
    secure_variables:
      NPM_TOKEN: "AES:zrPOXdWUAMyHo8N7EDQYPg==:BNjo2Pa0SkQMXurcJpVWE6VR+qLYzVP1TXTi7P91L+a4+Pmqoi6BlN3TdsLtT9eu"
      CC_TEST_REPORTER_ID: "AES:weNufwgbFfTeGGunxlVQnA==:2M+IAjaPjHZ2kVMLM2GNpLA49X1d5V5VGmqJxQaTvXAgkYtRUDZoBTiEAOTxr7s8ycnwsqiTtozlUs4J6Zutp93hfUbaRNAGVCTOFdp+wb4="
    stages:
      - tests:
          jobs:
            tests:
              tabs:
                Coverage: ./coverage/lcov-report/index.html
              tasks:
                - script: |
                    ./auto/code-climate-reporter before-build
                    ./auto/test --verbose --coverage
                    ./auto/code-climate-reporter after-build
                    docker run -v `pwd`:/tmp/mount alpine chown -R $(id -u):$(id -g) /tmp/mount
                - script: |
                    ./auto/clean-up || true
              artifacts:
                - test:
                    source: coverage/
                    destination: ./coverage/
            lint:
              tasks:
                - script: |
                    ./auto/yarn lint
            audit:
              tasks:
                - script: |
                    ./auto/clean-up || true
                - script: |
                    ##./auto/audit --json --groups dependencies --level moderate
                    echo -- Skip, stryker and jest have a vulnerability
            e2e-broken-clients:
              tasks:
                - script: |
                    ./auto/clean-up || true
                - script: |
                    set -e
                    ./auto/yarn ts-node src/bin/cli.ts transliterate
                    ./auto/yarn test:e2e
                    docker run -v `pwd`:/tmp/mount alpine chown -R $(id -u):$(id -g) /tmp/mount


  analytics-sdk-generator-extra-tests:
    group: analytics-sdk-generator
    label_template: "${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: analytics-sdk-generator-test
        stage: tests
      git-analytics-sdk-generator:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/leprechaun/analytics-sdk-generator.git
          branchwhitelist: master,test-*
        destination: ./

    environment_variables: {}
    secure_variables:
      STRYKER_DASHBOARD_API_KEY: "AES:U68JXa1abYM1DA5i58291Q==:gzS9JXlo68GJYoRPQ6JhqgXojXEXAbxdijlBG6uZ/9G6qytL/b4wE2dsuyQUGtQO"
    stages:
      - mutation:
          tasks:
            - script: |
                ./auto/mutation
                docker run -v `pwd`:/app/ alpine chown -R $(id -u):$(id -g) /app
          tabs:
            Mutation: ./reports/mutation/html/index.html
          artifacts:
            - test:
                source: reports/
                destination: ./reports/

  analytics-sdk-generator-build:
    group: analytics-sdk-generator
    label_template: "0.1.${COUNT}-${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: analytics-sdk-generator-test
        stage: tests
      git-analytics-sdk-generator:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/leprechaun/analytics-sdk-generator.git
          branchwhitelist: master,test-*
        destination: ./

    environment_variables: {}
    secure_variables:
      NPM_TOKEN: "AES:zrPOXdWUAMyHo8N7EDQYPg==:BNjo2Pa0SkQMXurcJpVWE6VR+qLYzVP1TXTi7P91L+a4+Pmqoi6BlN3TdsLtT9eu"
    stages:
      - package:
          tasks:
            - script: |
               set -e
               function finish {
                  EXIT_CODE=$?
                  docker run -v `pwd`:/tmp/mount alpine chown -R $(id -u):$(id -g) /tmp/mount
                  ./auto/clean-up || true
                  exit $EXIT_CODE
                }
                trap finish EXIT

                ./auto/build
                ./auto/publish --new-version ${GO_PIPELINE_LABEL} --tag beta

  analytics-sdk-generator-publish:
    group: analytics-sdk-generator
    label_template: "${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: analytics-sdk-generator-build
        stage: package
      git-analytics-sdk-generator:
        plugin_configuration:
          id: git.fb
          version: 1.3.5
        options:
          url: https://github.com/leprechaun/analytics-sdk-generator.git
          branchwhitelist: master,test-*
        destination: ./
    environment_variables: {}
    secure_variables:
      NPM_TOKEN: "AES:zrPOXdWUAMyHo8N7EDQYPg==:BNjo2Pa0SkQMXurcJpVWE6VR+qLYzVP1TXTi7P91L+a4+Pmqoi6BlN3TdsLtT9eu"
    stages:
      - publish:
          approval: manual
          jobs:
            publish:
              tasks:
                - script: |
                   set -e
                   function finish {
                      EXIT_CODE=$?
                      docker run -v `pwd`:/tmp/mount alpine chown -R $(id -u):$(id -g) /tmp/mount
                      ./auto/clean-up || true
                      exit $EXIT_CODE
                    }
                    trap finish EXIT

                    ./auto/build
                    ./auto/publish --new-version "$(echo $GO_PIPELINE_LABEL | awk -F '-' '{print $1}')"
